# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hahe.models


class Migration(migrations.Migration):

    dependencies = [
        ('hahe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardControlDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='hahe.Product')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Completed', hahe.models.IntegerRangeField(default=0)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hahe.Product')),
            ],
        ),
    ]
