# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hahe', '0002_dashboardcontroldevice_devicehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=100)),
                ('StartDelta', models.IntegerField(default=0)),
                ('EndDelta', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=100)),
                ('Poc1', models.CharField(blank=True, default='', max_length=100)),
                ('Poc1_email', models.EmailField(blank=True, default='', max_length=100)),
                ('Poc2', models.CharField(blank=True, default='', max_length=100)),
                ('Poc2_email', models.EmailField(blank=True, default='', max_length=100)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hahe.DefaultDevice')),
            ],
        ),
        migrations.CreateModel(
            name='TeamHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hahe.Product')),
                ('team', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='hahe.Team')),
            ],
        ),
        migrations.AddField(
            model_name='defaulttask',
            name='Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hahe.DefaultTeam'),
        ),
    ]
