# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahe', '0003_auto_20170810_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttask',
            name='EndDelta',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='defaulttask',
            name='StartDelta',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
