# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahe', '0004_auto_20170810_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='AssignedUser',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='defaulttask',
            name='EndDelta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='defaulttask',
            name='StartDelta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
