# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hahe', '0005_auto_20170816_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttask',
            name='AssignedUser',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='defaulttask',
            name='DependentTask',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='defaulttask',
            name='IsPostLaunch',
            field=models.BooleanField(default=False),
        ),
    ]
