# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=100)),
                ('StartDelta', models.IntegerField(blank=True, default=0, null=True)),
                ('EndDelta', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=100)),
                ('Poc1', models.CharField(blank=True, default='', max_length=100)),
                ('Poc1_email', models.EmailField(blank=True, default='', max_length=100)),
                ('Poc2', models.CharField(blank=True, default='', max_length=100)),
                ('Poc2_email', models.EmailField(blank=True, default='', max_length=100)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.DefaultDevice')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='defaulttask',
            name='Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.DefaultTeam'),
        ),
    ]
