# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20170818_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Completed', general.models.IntegerRangeField(default=0)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Product')),
            ],
        ),
    ]
