# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('LaunchDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poc1', models.CharField(default='', max_length=100)),
                ('Poc1_email', models.EmailField(default='', max_length=100)),
                ('poc2', models.CharField(default='', max_length=100)),
                ('poc3_email', models.EmailField(default='', max_length=100)),
                ('Project_KickOff_Meeting_Start_Date', models.DateField()),
                ('Project_KickOff_Meeting_End_Date', models.DateField()),
                ('Receive_PR_Samples_Start_Date', models.DateField()),
                ('Receive_PR_Samples_End_Date', models.DateField()),
                ('Develop_Schedule_Req_Start_Date', models.DateField()),
                ('Develop_Schedule_Req_End_Date', models.DateField()),
                ('Determine_Field_Test_Req_Start_Date', models.DateField()),
                ('Determine_Field_Test_Req_End_Date', models.DateField()),
                ('Marketing_Deck_Distribution_Start_Date', models.DateField()),
                ('Marketing_Deck_Distribution_End_Date', models.DateField()),
                ('User_Manual_Distribution_Start_Date', models.DateField()),
                ('User_Manual_Distribution_End_Date', models.DateField()),
                ('Distribute_Full_List_Of_SKUs_Start_date', models.DateField()),
                ('Production_Samples_Start_Date', models.DateField()),
                ('Production_Samples_End_Date', models.DateField()),
                ('User_Manuals_Start_Date', models.DateField()),
                ('User_Manuals_End_Date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='ProductReadiness',
            field=models.ManyToManyField(to='login.ProductReadiness'),
        ),
    ]
