# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170609_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreadiness',
            name='Poc1',
            field=models.CharField(default='Patrick koo', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='Poc1_email',
            field=models.EmailField(default='patrick.koo@samsung.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='poc2',
            field=models.CharField(default='Micheal Vigliotti', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='poc3_email',
            field=models.EmailField(default='m.vigliotti@samsung.com', max_length=100),
        ),
    ]
