# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_device_device_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ProductReadiness',
        ),
        migrations.AddField(
            model_name='device',
            name='ProductReadiness',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.ProductReadiness'),
        ),
    ]
