# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20170614_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='ProductReadiness',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
    ]
