# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20170614_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreadiness',
            name='Distribute_Full_List_Of_SKUs_End_date',
            field=models.DateField(null=True),
        ),
    ]
