# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_productreadiness_distribute_full_list_of_skus_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReadinessStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ProductReadiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness')),
            ],
        ),
    ]
