# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_productreadinessstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreadinessstatus',
            old_name='ProductReadiness',
            new_name='Product_Readiness',
        ),
    ]
