# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20170615_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreadinessstatus',
            name='Product_Readiness',
        ),
    ]
