# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_remove_productreadinessstatus_product_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreadinessstatus',
            name='Product_Readiness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
    ]
