# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0017_productreadinessstatus_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Determine_Field_Test_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Determine_Field_Test_post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateField(null=True)),
                ('Product_Readiness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Develop_Schedule_Req_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Develop_Schedule_Req_post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateField(null=True)),
                ('Product_Readiness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distribute_Full_List_Of_SKUs_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distribute_Full_List_Of_SKUs_post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateField(null=True)),
                ('Product_Readiness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marketing_Deck_Distribution_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marketing_Deck_Distribution_post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateField(null=True)),
                ('Product_Readiness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Production_Samples_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Production_Samples_post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateField(null=True)),
                ('Product_Readiness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_KickOff_Meeting_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_KickOff_Meeting_post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateField(null=True)),
                ('Product_Readiness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receive_PR_Samples_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receive_PR_Samples_post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateField(null=True)),
                ('Product_Readiness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Manual_Distribution_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Manual_Distribution_post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateField(null=True)),
                ('Product_Readiness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Manuals_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Manuals_post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateField(null=True)),
                ('Product_Readiness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productreadinessstatus',
            name='completed_date',
            field=models.DateField(null=True),
        ),
    ]
