# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20170621_1000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_KickOff_Meeting_Status',
            new_name='ProjectKickOffMeetingStatus',
        ),
    ]
