# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_auto_20170621_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectkickoffmeetingstatus',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
