# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20170621_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='determine_field_test_status',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='develop_schedule_req_status',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='distribute_full_list_of_skus_status',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='marketing_deck_distribution_status',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='production_samples_status',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='productreadinessstatus',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='projectkickoffmeetingstatus',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='receive_pr_samples_status',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='user_manual_distribution_status',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='user_manuals_status',
            name='completed_date',
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Determine_Field_Test_Req_complete_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Develop_Schedule_Req_complete_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Distribute_Full_List_Of_SKUs_complete_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Marketing_Deck_Distribution_complete_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Production_Samples_complete_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Project_KickOff_Meeting_complete_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Receive_PR_Samples_complete_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='User_Manual_Distribution_complete_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='User_Manuals_complete_date',
            field=models.DateField(null=True),
        ),
    ]
