# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20170621_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Determine_Field_Test_Status',
            new_name='DetermineFieldTestStatus',
        ),
        migrations.RenameModel(
            old_name='Marketing_Deck_Distribution_Status',
            new_name='DevelopScheduleReqStatus',
        ),
        migrations.RenameModel(
            old_name='Develop_Schedule_Req_Status',
            new_name='DistributeFullListOfSKUsStatus',
        ),
        migrations.RenameModel(
            old_name='Distribute_Full_List_Of_SKUs_Status',
            new_name='MarketingDeckDistributionStatus',
        ),
        migrations.RenameModel(
            old_name='Receive_PR_Samples_Status',
            new_name='ProductionSamplesStatus',
        ),
        migrations.RenameModel(
            old_name='User_Manual_Distribution_Status',
            new_name='ReceivePRSamplesStatus',
        ),
        migrations.RenameModel(
            old_name='User_Manuals_Status',
            new_name='UserManualDistributionStatus',
        ),
        migrations.RenameModel(
            old_name='Production_Samples_Status',
            new_name='UserManualsStatus',
        ),
        migrations.RenameField(
            model_name='developschedulereqstatus',
            old_name='Marketing_Deck_Distribution_post',
            new_name='Develop_Schedule_Req_post',
        ),
        migrations.RenameField(
            model_name='distributefulllistofskusstatus',
            old_name='Develop_Schedule_Req_post',
            new_name='Distribute_Full_List_Of_SKUs_post',
        ),
        migrations.RenameField(
            model_name='marketingdeckdistributionstatus',
            old_name='Distribute_Full_List_Of_SKUs_post',
            new_name='Marketing_Deck_Distribution_post',
        ),
        migrations.RenameField(
            model_name='productionsamplesstatus',
            old_name='Receive_PR_Samples_post',
            new_name='Production_Samples_post',
        ),
        migrations.RenameField(
            model_name='receiveprsamplesstatus',
            old_name='User_Manual_Distribution_post',
            new_name='Receive_PR_Samples_post',
        ),
        migrations.RenameField(
            model_name='usermanualdistributionstatus',
            old_name='User_Manuals_post',
            new_name='User_Manual_Distribution_post',
        ),
        migrations.RenameField(
            model_name='usermanualsstatus',
            old_name='Production_Samples_post',
            new_name='User_Manuals_post',
        ),
    ]
