# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20170621_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreadiness',
            name='Time_Delta_For_Warning',
            field=models.IntegerField(default=7),
        ),
    ]
