# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0024_productreadiness_time_delta_for_warning'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraTasks_VideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExtraTask_Name', models.CharField(default='', max_length=100)),
                ('ExtraTask_Start_Date', models.DateField(blank=True, null=True)),
                ('ExtraTask_End_Date', models.DateField(blank=True, null=True)),
                ('ExtraTask_complete_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraTaskStatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ExtraTasksVideoContent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ExtraTasks_VideoContent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task10StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task11StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task12StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task13StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task14StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task15StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task16StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task17StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task18StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task19StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task1StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task20StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task2StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task3StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task4StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task5StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task6StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task7StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task8StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task9StatusVideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='videocontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poc1', models.CharField(default='Allison Graham', max_length=100)),
                ('Poc1_email', models.EmailField(default='a1.graham@partner.samsung.com', max_length=100)),
                ('poc2', models.CharField(default='Nicole Cantwell', max_length=100)),
                ('poc3_email', models.EmailField(default='n.waud@samsung.com', max_length=100)),
                ('Task1_Name', models.CharField(default='Product Information (received)', max_length=100)),
                ('Task1_Start_Date', models.DateField(blank=True, null=True)),
                ('Task1_End_Date', models.DateField(blank=True, null=True)),
                ('Task1_complete_date', models.DateField(blank=True, null=True)),
                ('Task2_Name', models.CharField(default='Pre-Production Sample (received)', max_length=100)),
                ('Task2_Start_Date', models.DateField(blank=True, null=True)),
                ('Task2_End_Date', models.DateField(blank=True, null=True)),
                ('Task2_complete_date', models.DateField(blank=True, null=True)),
                ('Task3_Name', models.CharField(default='Topic Lists', max_length=100)),
                ('Task3_Start_Date', models.DateField(blank=True, null=True)),
                ('Task3_End_Date', models.DateField(blank=True, null=True)),
                ('Task3_complete_date', models.DateField(blank=True, null=True)),
                ('Task4_Name', models.CharField(default='Production Sample (received)', max_length=100)),
                ('Task4_Start_Date', models.DateField(blank=True, null=True)),
                ('Task4_End_Date', models.DateField(blank=True, null=True)),
                ('Task4_complete_date', models.DateField(blank=True, null=True)),
                ('Task5_Name', models.CharField(default='Scripts', max_length=100)),
                ('Task5_Start_Date', models.DateField(blank=True, null=True)),
                ('Task5_End_Date', models.DateField(blank=True, null=True)),
                ('Task5_complete_date', models.DateField(blank=True, null=True)),
                ('Task6_Name', models.CharField(default='Finalize Video', max_length=100)),
                ('Task6_Start_Date', models.DateField(blank=True, null=True)),
                ('Task6_End_Date', models.DateField(blank=True, null=True)),
                ('Task6_complete_date', models.DateField(blank=True, null=True)),
                ('Task7_Name', models.CharField(default='', max_length=100)),
                ('Task7_Start_Date', models.DateField(blank=True, null=True)),
                ('Task7_End_Date', models.DateField(blank=True, null=True)),
                ('Task7_complete_date', models.DateField(blank=True, null=True)),
                ('Task8_Name', models.CharField(default='', max_length=100)),
                ('Task8_Start_Date', models.DateField(blank=True, null=True)),
                ('Task8_End_Date', models.DateField(blank=True, null=True)),
                ('Task8_complete_date', models.DateField(blank=True, null=True)),
                ('Task9_Name', models.CharField(default='', max_length=100)),
                ('Task9_Start_Date', models.DateField(blank=True, null=True)),
                ('Task9_End_Date', models.DateField(blank=True, null=True)),
                ('Task9_complete_date', models.DateField(blank=True, null=True)),
                ('Task10_Name', models.CharField(default='', max_length=100)),
                ('Task10_Start_Date', models.DateField(blank=True, null=True)),
                ('Task10_End_Date', models.DateField(blank=True, null=True)),
                ('Task10_complete_date', models.DateField(blank=True, null=True)),
                ('Task11_Name', models.CharField(default='', max_length=100)),
                ('Task11_Start_Date', models.DateField(blank=True, null=True)),
                ('Task11_End_Date', models.DateField(blank=True, null=True)),
                ('Task11_complete_date', models.DateField(blank=True, null=True)),
                ('Task12_Name', models.CharField(default='', max_length=100)),
                ('Task12_Start_Date', models.DateField(blank=True, null=True)),
                ('Task12_End_Date', models.DateField(blank=True, null=True)),
                ('Task12_complete_date', models.DateField(blank=True, null=True)),
                ('Task13_Name', models.CharField(default='', max_length=100)),
                ('Task13_Start_Date', models.DateField(blank=True, null=True)),
                ('Task13_End_Date', models.DateField(blank=True, null=True)),
                ('Task13_complete_date', models.DateField(blank=True, null=True)),
                ('Task14_Name', models.CharField(default='', max_length=100)),
                ('Task14_Start_Date', models.DateField(blank=True, null=True)),
                ('Task14_End_Date', models.DateField(blank=True, null=True)),
                ('Task14_complete_date', models.DateField(blank=True, null=True)),
                ('Task15_Name', models.CharField(default='', max_length=100)),
                ('Task15_Start_Date', models.DateField(blank=True, null=True)),
                ('Task15_End_Date', models.DateField(blank=True, null=True)),
                ('Task15_complete_date', models.DateField(blank=True, null=True)),
                ('Task16_Name', models.CharField(default='', max_length=100)),
                ('Task16_Start_Date', models.DateField(blank=True, null=True)),
                ('Task16_End_Date', models.DateField(blank=True, null=True)),
                ('Task16_complete_date', models.DateField(blank=True, null=True)),
                ('Task17_Name', models.CharField(default='', max_length=100)),
                ('Task17_Start_Date', models.DateField(blank=True, null=True)),
                ('Task17_End_Date', models.DateField(blank=True, null=True)),
                ('Task17_complete_date', models.DateField(blank=True, null=True)),
                ('Task18_Name', models.CharField(default='', max_length=100)),
                ('Task18_Start_Date', models.DateField(blank=True, null=True)),
                ('Task18_End_Date', models.DateField(blank=True, null=True)),
                ('Task18_complete_date', models.DateField(blank=True, null=True)),
                ('Task19_Name', models.CharField(default='', max_length=100)),
                ('Task19_Start_Date', models.DateField(blank=True, null=True)),
                ('Task19_End_Date', models.DateField(blank=True, null=True)),
                ('Task19_complete_date', models.DateField(blank=True, null=True)),
                ('Task20_Name', models.CharField(default='', max_length=100)),
                ('Task20_Start_Date', models.DateField(blank=True, null=True)),
                ('Task20_End_Date', models.DateField(blank=True, null=True)),
                ('Task20_complete_date', models.DateField(blank=True, null=True)),
                ('Time_Delta_For_Warning', models.IntegerField(default=7)),
                ('completed', login.models.IntegerRangeField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='Determine_Field_Test_Req_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='Develop_Schedule_Req_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='Distribute_Full_List_Of_SKUs_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='Marketing_Deck_Distribution_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='Production_Samples_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='Project_KickOff_Meeting_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='Receive_PR_Samples_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='User_Manual_Distribution_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='User_Manuals_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task9statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task9statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task8statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task8statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task7statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task7statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task6statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task6statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task5statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task5statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task4statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task4statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task3statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task3statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task2statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task2statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task20statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task20statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task1statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task1statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task19statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task19statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task18statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task18statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task17statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task17statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task16statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task16statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task15statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task15statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task14statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task14statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task13statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task13statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task12statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task12statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task11statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task11statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task10statusvideocontent',
            name='VideoContent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='task10statusvideocontent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extratasks_videocontent',
            name='videocontent_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
        migrations.AddField(
            model_name='device',
            name='VideoContet',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='login.videocontent'),
        ),
    ]
