# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20170626_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='VideoContet',
            new_name='VideoContent',
        ),
    ]
