# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_auto_20170626_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrataskstatusvideocontent',
            name='ExtraTasksVideoContent',
        ),
        migrations.RemoveField(
            model_name='extrataskstatusvideocontent',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExtraTaskStatusVideoContent',
        ),
    ]
