# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0032_auto_20170629_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task11StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task12StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task13StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task14StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task15StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task16StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task17StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task18StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task19StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task1StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task20StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task2StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task3StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task4StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task5StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task6StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task7StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task8StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task9StatusProductReadiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductReadinessStatus',
            new_name='Task10StatusProductReadiness',
        ),
        migrations.RemoveField(
            model_name='determinefieldteststatus',
            name='Product_Readiness',
        ),
        migrations.RemoveField(
            model_name='determinefieldteststatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='developschedulereqstatus',
            name='Product_Readiness',
        ),
        migrations.RemoveField(
            model_name='developschedulereqstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='distributefulllistofskusstatus',
            name='Product_Readiness',
        ),
        migrations.RemoveField(
            model_name='distributefulllistofskusstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='marketingdeckdistributionstatus',
            name='Product_Readiness',
        ),
        migrations.RemoveField(
            model_name='marketingdeckdistributionstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productionsamplesstatus',
            name='Product_Readiness',
        ),
        migrations.RemoveField(
            model_name='productionsamplesstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectkickoffmeetingstatus',
            name='Product_Readiness',
        ),
        migrations.RemoveField(
            model_name='projectkickoffmeetingstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='receiveprsamplesstatus',
            name='Product_Readiness',
        ),
        migrations.RemoveField(
            model_name='receiveprsamplesstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermanualdistributionstatus',
            name='Product_Readiness',
        ),
        migrations.RemoveField(
            model_name='usermanualdistributionstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermanualsstatus',
            name='Product_Readiness',
        ),
        migrations.RemoveField(
            model_name='usermanualsstatus',
            name='user',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Determine_Field_Test_Req_complete_date',
            new_name='Task10_End_Date',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Develop_Schedule_Req_complete_date',
            new_name='Task10_Start_Date',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Determine_Field_Test_Req',
            new_name='Task10_alert',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Distribute_Full_List_Of_SKUs_complete_date',
            new_name='Task10_complete_date',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Develop_Schedule_Req',
            new_name='Task10_warning',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Marketing_Deck_Distribution_complete_date',
            new_name='Task11_End_Date',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Production_Samples_complete_date',
            new_name='Task11_Start_Date',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Distribute_Full_List_Of_SKUs',
            new_name='Task11_alert',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Project_KickOff_Meeting_complete_date',
            new_name='Task11_complete_date',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Marketing_Deck_Distribution',
            new_name='Task11_warning',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Receive_PR_Samples_complete_date',
            new_name='Task12_End_Date',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='User_Manual_Distribution_complete_date',
            new_name='Task12_Start_Date',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Production_Samples',
            new_name='Task12_alert',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='User_Manuals_complete_date',
            new_name='Task12_complete_date',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Project_KickOff_Meeting',
            new_name='Task12_warning',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='Receive_PR_Samples',
            new_name='Task13_alert',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='User_Manual_Distribution',
            new_name='Task13_warning',
        ),
        migrations.RenameField(
            model_name='productreadiness',
            old_name='User_Manuals',
            new_name='Task14_alert',
        ),
        migrations.RenameField(
            model_name='task10statusproductreadiness',
            old_name='Product_Readiness',
            new_name='Parts',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Determine_Field_Test_Req_End_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Determine_Field_Test_Req_Start_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Develop_Schedule_Req_End_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Develop_Schedule_Req_Start_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Distribute_Full_List_Of_SKUs_End_date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Distribute_Full_List_Of_SKUs_Start_date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Marketing_Deck_Distribution_End_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Marketing_Deck_Distribution_Start_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Production_Samples_End_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Production_Samples_Start_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Project_KickOff_Meeting_End_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Project_KickOff_Meeting_Start_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Receive_PR_Samples_End_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Receive_PR_Samples_Start_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Status_Details',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='Status_Time',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='User_Manual_Distribution_End_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='User_Manual_Distribution_Start_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='User_Manuals_End_Date',
        ),
        migrations.RemoveField(
            model_name='productreadiness',
            name='User_Manuals_Start_Date',
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Status',
            field=models.CharField(choices=[('On Time', 'On Time'), ('At Risk', 'At Risk'), ('Delayed', 'Delayed')], default='On_Time', max_length=10),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task10_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task11_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task12_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task13_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task13_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task13_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task13_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task14_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task14_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task14_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task14_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task14_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task15_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task15_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task15_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task15_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task15_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task15_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task16_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task16_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task16_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task16_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task16_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task16_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task17_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task17_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task17_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task17_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task17_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task17_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task18_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task18_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task18_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task18_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task18_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task18_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task19_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task19_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task19_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task19_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task19_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task19_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task1_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task1_Name',
            field=models.CharField(blank=True, default='Project Kickoff Meeting', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task1_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task1_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task1_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task1_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task20_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task20_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task20_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task20_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task20_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task20_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task2_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task2_Name',
            field=models.CharField(blank=True, default='Receive PR Samples from HQ', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task2_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task2_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task2_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task2_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task3_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task3_Name',
            field=models.CharField(blank=True, default='Develop Schedule and requirements', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task3_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task3_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task3_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task3_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task4_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task4_Name',
            field=models.CharField(blank=True, default='Determine Field Test Requirement', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task4_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task4_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task4_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task4_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task5_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task5_Name',
            field=models.CharField(blank=True, default='Marketing Deck Distribution', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task5_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task5_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task5_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task5_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task6_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task6_Name',
            field=models.CharField(blank=True, default='User Manual Distribution', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task6_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task6_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task6_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task6_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task7_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task7_Name',
            field=models.CharField(blank=True, default='Distribute Full List of SKUs', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task7_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task7_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task7_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task7_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task8_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task8_Name',
            field=models.CharField(blank=True, default='Production Samples (order/Send)', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task8_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task8_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task8_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task8_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task9_End_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task9_Name',
            field=models.CharField(blank=True, default='User Manuals (on.com)(received)', max_length=100),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task9_Start_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task9_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task9_complete_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreadiness',
            name='Task9_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='callcenteropertaions',
            name='Task1_Name',
            field=models.CharField(blank=True, default='Sales Forecast (received)', max_length=100),
        ),
        migrations.AlterField(
            model_name='callcenteropertaions',
            name='Task2_Name',
            field=models.CharField(blank=True, default='Define Support Hours (received)', max_length=100),
        ),
        migrations.AlterField(
            model_name='callcenteropertaions',
            name='Task3_Name',
            field=models.CharField(blank=True, default='Contact Volume Forecast', max_length=100),
        ),
        migrations.AlterField(
            model_name='callcenteropertaions',
            name='Task4_Name',
            field=models.CharField(blank=True, default='Staffing Plan (Voice & Digital)', max_length=100),
        ),
        migrations.AlterField(
            model_name='callcenteropertaions',
            name='Task5_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='callcentertraining',
            name='Task1_Name',
            field=models.CharField(blank=True, default='Product Information (received)', max_length=100),
        ),
        migrations.AlterField(
            model_name='callcentertraining',
            name='Task2_Name',
            field=models.CharField(blank=True, default='Create Training: Agents', max_length=100),
        ),
        migrations.AlterField(
            model_name='callcentertraining',
            name='Task3_Name',
            field=models.CharField(blank=True, default='Training Expectation Rollout', max_length=100),
        ),
        migrations.AlterField(
            model_name='callcentertraining',
            name='Task4_Name',
            field=models.CharField(blank=True, default='Training the trainer', max_length=100),
        ),
        migrations.AlterField(
            model_name='callcentertraining',
            name='Task5_Name',
            field=models.CharField(blank=True, default='Train: Agents', max_length=100),
        ),
        migrations.AlterField(
            model_name='callcentertraining',
            name='Task6_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='digitalcontent',
            name='Task1_Name',
            field=models.CharField(blank=True, default='Samples (received)', max_length=100),
        ),
        migrations.AlterField(
            model_name='digitalcontent',
            name='Task2_Name',
            field=models.CharField(blank=True, default='Pre-sales FAQ (received/posted)', max_length=100),
        ),
        migrations.AlterField(
            model_name='digitalcontent',
            name='Task3_Name',
            field=models.CharField(blank=True, default='Customer Content (samsung.com)', max_length=100),
        ),
        migrations.AlterField(
            model_name='digitalcontent',
            name='Task4_Name',
            field=models.CharField(blank=True, default='Agent Content: (Decision Tree)', max_length=100),
        ),
        migrations.AlterField(
            model_name='digitalcontent',
            name='Task5_Name',
            field=models.CharField(blank=True, default='Application: Samsung+(content)', max_length=100),
        ),
        migrations.AlterField(
            model_name='digitalcontent',
            name='Task6_Name',
            field=models.CharField(blank=True, default='Simulators', max_length=100),
        ),
        migrations.AlterField(
            model_name='digitalcontent',
            name='Task7_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='Poc1',
            field=models.CharField(default='Michael Vigliotti', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='Poc1_email',
            field=models.EmailField(default='m.vigliotti@samsung.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='poc2',
            field=models.CharField(default='Patrick Koo', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreadiness',
            name='poc3_email',
            field=models.EmailField(default='patrick.koo@samsung.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='productsupport',
            name='Task1_Name',
            field=models.CharField(blank=True, default='PV/PR Sample (received)', max_length=100),
        ),
        migrations.AlterField(
            model_name='productsupport',
            name='Task2_Name',
            field=models.CharField(blank=True, default='Serviceablity Test', max_length=100),
        ),
        migrations.AlterField(
            model_name='productsupport',
            name='Task3_Name',
            field=models.CharField(blank=True, default='Doc Review: Service Manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='productsupport',
            name='Task4_Name',
            field=models.CharField(blank=True, default='Doc Review: Box Art', max_length=100),
        ),
        migrations.AlterField(
            model_name='productsupport',
            name='Task5_Name',
            field=models.CharField(blank=True, default='PR Evaluation', max_length=100),
        ),
        migrations.AlterField(
            model_name='productsupport',
            name='Task6_Name',
            field=models.CharField(blank=True, default='UL/FCC/Agency Testing (received)', max_length=100),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='Task1_Name',
            field=models.CharField(default='Topic Lists', max_length=100),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='Task2_Name',
            field=models.CharField(default='Scripts', max_length=100),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='Task3_Name',
            field=models.CharField(blank=True, default='Finalize Video', max_length=100),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='Task4_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='Task5_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='Task6_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Task1_Name',
            field=models.CharField(blank=True, default='Packing Test (Pre-Production)', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Task2_Name',
            field=models.CharField(blank=True, default='Cross Inspection (Factory)', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Task3_Name',
            field=models.CharField(blank=True, default='Customer Experience Test', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Task4_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Task5_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='Task6_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='DetermineFieldTestStatus',
        ),
        migrations.DeleteModel(
            name='DevelopScheduleReqStatus',
        ),
        migrations.DeleteModel(
            name='DistributeFullListOfSKUsStatus',
        ),
        migrations.DeleteModel(
            name='MarketingDeckDistributionStatus',
        ),
        migrations.DeleteModel(
            name='ProductionSamplesStatus',
        ),
        migrations.DeleteModel(
            name='ProjectKickOffMeetingStatus',
        ),
        migrations.DeleteModel(
            name='ReceivePRSamplesStatus',
        ),
        migrations.DeleteModel(
            name='UserManualDistributionStatus',
        ),
        migrations.DeleteModel(
            name='UserManualsStatus',
        ),
        migrations.AddField(
            model_name='task9statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task9statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task8statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task8statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task7statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task7statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task6statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task6statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task5statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task5statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task4statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task4statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task3statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task3statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task2statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task2statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task20statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task20statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task1statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task1statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task19statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task19statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task18statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task18statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task17statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task17statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task16statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task16statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task15statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task15statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task14statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task14statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task13statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task13statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task12statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task12statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task11statusproductreadiness',
            name='Parts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.ProductReadiness'),
        ),
        migrations.AddField(
            model_name='task11statusproductreadiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
