# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_auto_20170629_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(default='')),
                ('Severity', models.CharField(choices=[('information', 'information'), ('warning', 'warning'), ('alert', 'alert')], default='information', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='callcentertraining',
            name='Task6_Name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
