# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_auto_20170703_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Launch_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, default=login.models.get_default_my_date, null=True)),
            ],
        ),
    ]
