# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_devicehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehistory',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device'),
        ),
    ]
