# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_devicehistory_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardControlDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
    ]
