# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_dashboardcontroldevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReadinessHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
    ]
