# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0042_productreadinesshistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenterOperationsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
        migrations.CreateModel(
            name='CallCenterTrainingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalContentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
        migrations.CreateModel(
            name='FieldServiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
        migrations.CreateModel(
            name='PartsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSupportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMarketingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTrainingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
        migrations.CreateModel(
            name='TechSupportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delayed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Completed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('DueSoon', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('OnTime', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Device')),
            ],
        ),
    ]
