# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-18 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_auto_20170811_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(blank=True, default='')),
                ('Severity', models.CharField(choices=[('information', 'information'), ('warning', 'warning'), ('alert', 'alert')], default='information', max_length=20)),
            ],
        ),
    ]
